<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-201607301632" ignored="0" name="用户管理系统测试用例" tests="7" failures="1" timestamp="20 十月 2019 11:30:37 GMT" time="4.471" errors="0">
  <testcase name="loginTrue" time="4.119" classname="com.sap.cases.LoginTest">
    <failure type="org.apache.http.conn.HttpHostConnectException" message="Connection to http://localhost:8889 refused">
      <![CDATA[org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8889 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:573)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:425)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:732)
	at com.sap.cases.LoginTest.getResult(LoginTest.java:59)
	at com.sap.cases.LoginTest.loginTrue(LoginTest.java:43)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:123)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	... 38 more
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- loginTrue -->
  <testcase name="loginFalse" time="0.087" classname="com.sap.cases.LoginTest"/>
  <testcase name="addUser" time="0.0" classname="com.sap.cases.AddUserTest">
    <skipped/>
  </testcase> <!-- addUser -->
  <testcase name="getUserInfo" time="0.0" classname="com.sap.cases.GetUserInfoTest">
    <skipped/>
  </testcase> <!-- getUserInfo -->
  <testcase name="updateUserInfo" time="0.0" classname="com.sap.cases.UpdateUserInfoTest">
    <skipped/>
  </testcase> <!-- updateUserInfo -->
  <testcase name="deleteUser" time="0.0" classname="com.sap.cases.UpdateUserInfoTest">
    <skipped/>
  </testcase> <!-- deleteUser -->
  <testcase name="getUserListInfo" time="0.0" classname="com.sap.cases.GetUserInfoListTest">
    <skipped/>
  </testcase> <!-- getUserListInfo -->
</testsuite> <!-- 用户管理系统测试用例 -->
